15.0 cancelled
Odoo-EC/l10n-ecuador pull request #18
Opened 2023-06-23 23:59 UTC by jorge-luis-dev

Cancelar comprobantes autroizados del SRI. Primero se debe hacer el proceso de anulación en el SRI después se realiza la acción de cancelar documento EDI

2023-07-04 04:27 UTC, celm1990 requested changes
@jorge-luis-dev 

Por favor no dejar loggers en cada metodo, para pruebas lo entiendo pero ya en el PR final quitarlos

Ademas los patch habiamos visto como hacerlos en 1 solo with para evitar tantas identaciones del codigo, que paso con eso finalmente?

2023-07-04 04:27 UTC, celm1990 commented on l10n_ec_account_edi/models/account_move.py
> +            _logger.warning("Cancelled receipt")
quitar estos logger

2023-07-04 04:27 UTC, celm1990 commented on l10n_ec_account_edi/models/account_move.py
> +            _logger.warning(f"{receipt.name} is_authorized -> {is_authorized}")
aqui tambien

2023-07-04 04:27 UTC, celm1990 commented on l10n_ec_account_edi/tests/test_l10n_ec_cancelled.py
> +        )
aqui

2023-07-04 04:27 UTC, celm1990 commented on l10n_ec_account_edi/tests/test_l10n_ec_cancelled.py
> +                    edi_doc._process_documents_web_services(with_commit=False)
hacer un solo patch, me parece que esto ya lo habiamos revisado, te falta subir el cambio o tuviste algun inconveniente segun lo que probamos?

2023-07-07 23:35 UTC, jorge-luis-dev commented on l10n_ec_account_edi/tests/test_l10n_ec_cancelled.py
> +                    edi_doc._process_documents_web_services(with_commit=False)
Hola, ya le voy a actualizar

2023-07-15 16:43 UTC, merged