15.0 certificate notify
Odoo-EC/l10n-ecuador pull request #38
Opened 2023-11-15 22:26 UTC by jorge-luis-dev

2023-11-18 22:15 UTC, celm1990 requested changes
@jorge-luis-dev

2023-11-18 22:15 UTC, celm1990 commented on l10n_ec_account_edi/data/cron_check_certificate.xml
> +        <field name="interval_type">minutes</field>
Creo q esta tarea cron deberia ejecutarse por defecto cada dia, cada minuto me parece muy intenso

2023-11-18 22:15 UTC, celm1990 commented on l10n_ec_account_edi/tests/test_l10n_ec_check_certificate.py
> +        self.assertTrue(result)
No entendi bien los test, tengamos presente que la intencion del test mas alla de cubrir el codigo deberia plantear escenarios que nos permita validar que dicho codigo esta funcionando bien.

Mi sugerencia en los test seria, crear certificados con diferentes fechas de expiracion y saber cuantos certificados estan caducados y se debieron notificar, para asi hacer algun assert que verifique los mensajes del chater y valide que efectivamente se envio el correo. Y asi mismo con aquellos que NO deberian ser notificados, otro assert que evalue los mensajes y NO tenga ningun mensaje posteado

Espero haberme explicado, me comentas alguna novedad

2023-11-18 22:15 UTC, celm1990 commented on l10n_ec_account_edi/views/sri_key_type_view.xml
> -                                filename="file_name"
Esta parte no deberia verse modificada, en una vista deberiamos tener la parte superior que se ve siempre, y luego en los page cada informacion adicional.
La informacion principal deberia estar siempre disponible en la parte superior

![image](https://github.com/Odoo-EC/l10n-ecuador/assets/7775116/e7982143-9691-4d04-ad15-52d775a31242)

2023-11-20 17:21 UTC, jorge-luis-dev commented on l10n_ec_account_edi/data/cron_check_certificate.xml
> +        <field name="interval_type">minutes</field>
Hola Carlos, cierto, se me paso

2023-12-04 04:32 UTC, merged